jms_serializer:
    handlers:
        datetime:
            default_format: 'd/m/Y'
            default_timezone: 'UTC'

    metadata:
        auto_detetion: true
        directories:
           DomainModel:
               namespace_prefix: Domain\Model
               path: 'Kernel.root_dir/Resources/infrastructure/serializer/jms'